* Proyecto: Optimización logística para distribución de Despensas. 
** Definición 
*** Variables:
- *Hogares*: Direcciones postales con coordenadas (lat,long) a las cuales se 
- *Centros de Distribución*: Centros en los que se almacenan las despensas y luego de ahí salen las cuadrillas a repartirlas.
- *Cuadrillas*: Grupos de diversas dependencias que saldrán a entregar las despensas, cada uno es responsable de guardar su evidencia de la entrega. Hay más de una cuadrilla por centro de distribución. 
- *Despensas*: Hay al menos 4 tipos de despensas:
  - Adultos mayores.
  - Enfermos COVID-19
  - Familias con niños.
  - Familias sin niños.

*** Sistemas. 

Necesitamos dos sistemas: 

- Generar la distribución de insumos necesarios entre los diversos centros de distribución.
- Generar el orden en el que las cuadrillas tendrán que repartir las distintas despensas. 
** Problemas
*** Distribución de insumos necesarios. 
Dada la demanda de despensas (serie de coordenadas y el tipo de despensa dd = (lat,long, td) ), y centros de distribución (coordenadas cd = (lat,long)). Encontrar La asignación óptima de los hogares a cada centro de distribución. 
*** Planeación de rutas. 
Dado un número de cuadrillas, con la demanda asignada al centro de distribución, tenemos que encontrar el orden de visita para cada uno de los hogares que cada cuadrilla visitará. Se busca que el problema sea óptimo y se minimice el tiempo en calle de cada una de las cuadrillas. 
** Lenguaje 
Se busca que el lenguaje para programar la API sea Python 3.7. Manejado con Anaconda(o miniconda), para el versionamiento de paquetes. La librería para manejar la API será Flask.  
** Infraestructura. 
Se requiere que se produzca una imagen de Docker para poder exportar todo en contenedores. 
